name: backend-cd

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Create application.properties
        working-directory: ./backend/src/main/resources
        run: |
          touch application.properties
          echo "spring.application.name=cs-2340-p2-api" >> ./application.properties
          echo "spring.datasource.url=${{ secrets.API_SPRING_DATASOURCE_URL }}" >> ./application.properties
          echo "spring.datasource.username=${{ secrets.API_SPRING_DATASOURCE_USERNAME }}" >> ./application.properties
          echo "spring.datasource.password=${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}" >> ./application.properties
          echo "spring.jpa.hibernate.ddl-auto=validate" >> ./application.properties
          echo "openai.api-key=${{ secrets.API_OPENAI_API_KEY }}" >> ./application.properties

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        working-directory: ./backend
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mvn -ntp clean verify
          docker build . -t michaelyi/cs-2340-p2-api:latest
          docker build . -t michaelyi/cs-2340-p2-api:${{ env.VERSION }}
          docker push michaelyi/cs-2340-p2-api:latest
          docker push michaelyi/cs-2340-p2-api:${{ env.VERSION }}
          echo "$SSH_PRIVATE_KEY" > cs-2340-p2-api-kp.pem
          chmod 400 cs-2340-p2-api-kp.pem
          ssh -o StrictHostKeyChecking=no -i cs-2340-p2-api-kp.pem ec2-user@${SSH_HOST} '
            sudo docker stop cs-2340-p2-api || true
            sudo docker rm cs-2340-p2-api || true
            sudo docker rmi -f $(sudo docker image ls -a -q)
            sudo docker pull michaelyi/cs-2340-p2-api:latest
            sudo docker run --name cs-2340-p2-api -d -p 8080:8080 michaelyi/cs-2340-p2-api:latest
            '
