name: frontend-cd

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle


      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        working-directory: ./frontend
        env:
          # SSH_HOST: ${{ secrets.SSH_HOST }}
          # SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          gradle check --stacktrace